---
- name: "Deploying Updates to development-server"
  hosts: "development-server"
  vars:
    server: development-server
  become: yes
  tasks:
    - name: Testing variables
      debug:
        msg: "server_port: {{ server_port }}"
    - name: Copying app folder to Server
      copy:
        src: /home/philipp/cs/abad/app
        directory_mode: yes
        dest: /var/www/abad
        owner: root
        group: root
    - name: Copying Systemd Service File to Server
      template:
        src: templates/abad.service
        dest: /etc/systemd/system
        owner: root
        group: root
    - name: Restarting abad
      systemd:
        name: abad
        daemon_reload: yes
        state: restarted
        enabled: yes