---
- name: Setting up Host
  hosts: develop-server
  vars:
    server_port: 80
  become: yes

  tasks:
  - name: Ensuring Python3 is present
    apt:
        name: python3
        state: present
  - name: Ensuring Virtualenv is present
    apt:
        name: virtualenv
        state: present
  - name: Cloning Git Repository
    git:
        repo: https://github.com/lipflip010/abad.git
        dest: /var/www/abad
        force: yes
        version: develop
        accept_hostkey: yes
  - name: Building Python Project
    pip:
        requirements: /var/www/abad/requirements.txt
        virtualenv: /var/www/abad/env
        virtualenv_python: python3
  - name: Copying Systemd Service File to Server
    template:
      src: templates/abad.service
      dest: /etc/systemd/system
      owner: root
      group: root
  - name: Starting abad
    systemd:
      name: abad
      daemon_reload: yes
      state: restarted
      enabled: yes

