---
- name: "Deploying Updates to {{ server }}-server"
  hosts: "{{ server }}-server"
  become: yes
  tasks:
    - name: Testing variables
      debug:
        msg: "server_port: {{ server_port }}"
    - name: Updating Repository
      git:
        repo: https://github.com/lipflip010/abad.git
        dest: /var/www/abad
        force: yes
        version: develop
        accept_hostkey: yes
#    - name: Updating python dependencies
#      pip:
#        requirements: /var/www/abad/requirements.txt
#        virtualenv: /var/www/abad/env
#        virtualenv_python: python3
    - name: Copying Systemd Service File to Server
      template:
        src: templates/abad.service
        dest: /etc/systemd/system
        owner: root
        group: root
    - name: Restarting abad
      systemd:
        name: abad
        daemon_reload: yes
        state: restarted
        enabled: yes