---
- name: "Retrieving sar logs from {{ server }}-server"
  hosts: "{{ server }}-server"
  become: yes
  tasks:
    - name: Archiving sysstat folder
      archive:
        path: /var/log/sysstat/*
        dest: /var/log/{{ ansible_date_time.date }}_sysstat.gz
        format: gz
    - name: Copying folder to local system
      fetch:
        src: /var/log/{{ ansible_date_time.date }}_sysstat.gz
        dest: /home/philipp/Backup/normandy/logs/
        flat: yes
    - name: Removing archive on remote
      file:
        path: /var/log/{{ ansible_date_time.date }}_sysstat.gz
        state: absent

